version: '{build}'

environment:
  JAVA_OPTS: -Dfile.encoding=UTF8
  SBT_OPTS: -Dfile.encoding=UTF8
  SBT_HOME: "%USERPROFILE%\\sbt"
  matrix:
    - JDK: 8
    - JDK: 11

install:
  - cmd: choco install sbt -ia "INSTALLDIR=""%SBT_HOME%"""
  - ps: (new-object net.webclient).DownloadFile('https://raw.githubusercontent.com/shyiko/jabba/master/install.ps1', 'install.ps1')
  - ps: powershell ". ""install.ps1"""
  - ps: jabba install "adopt@1.$($Env:JDK).0-0"
  - ps: jabba use "adopt@1.$($Env:JDK).0-0"
  - ps: java -Xmx32m -version

build_script:
  - sbt compile

test_script:
  - sbt test

cache:
  - "%USERPROFILE%\\.sbt"
  - "%USERPROFILE%\\.ivy2\\cache"
  - "%USERPROFILE%\\.jabba"
