version: '{build}'
os: Windows Server 2012
environment:
  JAVA_OPTS: -Dfile.encoding=UTF8
  SBT_OPTS: -Dfile.encoding=UTF8
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - cmd: choco install sbt -ia "INSTALLDIR=""C:\sbt"""
  - cmd: SET PATH=C:\sbt\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-Xmx4G -XX:MaxPermSize=1G
build_script:
  - sbt compile
test_script:
  # -Djna.nosys=true is required to avoid the following error:
  # There is an incompatible JNA native library installed on this system
  #
  # There is an issue in sbt-io about it:
  # https://github.com/sbt/io/issues/110
  - sbt -Djna.nosys=true test
